name: flutter_canvas_code_editor
description: An editor for Dart code, built with the Flutter canvas.
publish_to: 'none'
version: 0.0.0-a1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file: ^7.0.0
  file_picker: ^5.3.3
  path: ^1.8.3

  abstractions:
    git: https://github.com/enspyrco/abstractions
  error_correction_in_perception:
    git: https://github.com/enspyrco/error_correction_in_perception
  framing_in_perception:
    git: https://github.com/enspyrco/framing_in_perception
  introspection:
    git: https://github.com/enspyrco/introspection
  locator_for_perception:
    git: https://github.com/enspyrco/locator_for_perception
  percepts:
    git: https://github.com/enspyrco/percepts
  test_utils_for_perception:
    git: https://github.com/enspyrco/test_utils_for_perception

dev_dependencies:
  flutter_test:
    sdk: flutter
  enspyr_lints:
    git: https://github.com/enspyrco/enspyr_lints

flutter:
  uses-material-design: true
