name: flutter_canvas_code_editor
description: An editor for Dart code, built with the Flutter canvas.
publish_to: 'none'
version: 0.0.0-a1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  enspyr_lints:
    git: https://github.com/enspyrco/enspyr_lints

flutter:
  uses-material-design: true
